(defun add (a b)
    (+ a b))
(defun add (a::int b::int)
    (addInt a b))
(defun add (a::float b::int)
    (addFloat a (:: float b)))
(defun add (a::int b::float)
    (addFloat (::float a) b))
(defun add (a::float b::float)
    (addFloat a b))

(defun sub (a b)
    (- a b))
(defun sub (a::int b::int)
    (addInt a b))
(defun add (a::float b::int)
    (addFloat a (:: float b)))
(defun add (a::int b::float)
    (addFloat (:: float a) b))
(defun add (a::float b::float)
    (addFloat a b))
